services:
  itu_change:
    image: jcivitell/itu_change
    container_name: itu_change
    build:
      context: .
      dockerfile: ./Dockerfile
      tags:
      - "jcivitell/itu_change:${CIRCLE_TAG:-notag}"
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ./ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=llama2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]